// Example app deps, not necessarily needed for tor usage.
import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
// Imports needed for tor usage:
import 'package:socks5_proxy/socks_client.dart'; // Just for example; can use any socks5 proxy package, pick your favorite.
import 'package:tor_ffi_plugin/tor_ffi_plugin.dart';
import 'package:tor_package/tor_package.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  // Flag to track if tor has started.
  bool torIsRunning = false;

  // Set the default text for the host input field.
  final hostController = TextEditingController(text: 'https://icanhazip.com/');
  // https://check.torproject.org is another good option.

  Future<void> startTor() async {
    // Start the Tor daemon.
    await Tor.instance.start(
      torDataDirPath: (await getApplicationSupportDirectory()).path,
    );

    // Toggle started flag.
    setState(() {
      torIsRunning = Tor.instance.status == TorStatus.on; // Update flag
    });

    print('Done awaiting; tor should be running');
  }

  @override
  void dispose() {
    // Clean up the controller when the widget is disposed.
    hostController.dispose();
    super.dispose();
  }

  // TODO remove unneeded autogenerated/template code below.
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    const spacerSmall = SizedBox(height: 10);
    return Scaffold(
      appBar: AppBar(
        title: const Text('Tor example'),
      ),
      body: SingleChildScrollView(
        child: Container(
          padding: const EdgeInsets.all(10),
          child: Column(
            children: [
              // An explainer paragraph of test containing a walkthrough for the
              // proof of concept.
              const Text("1. Click the `Start tor` button to start Tor A\n"
                  "2. Click the `Make proxied request` button to start get Tor Address A\n"
                  "3. Click the `Test tor_package` button to start Tor B and get Tor Address B\n"
                  "4. Compare the two addresses printed to the console."),
              // A spacer.
              spacerSmall,
              TextButton(
                onPressed: torIsRunning
                    ? null
                    : () async {
                        unawaited(
                          showDialog(
                            barrierDismissible: false,
                            context: context,
                            builder: (_) => const Dialog(
                              child: Padding(
                                padding: EdgeInsets.all(20.0),
                                child: Text("Starting tor..."),
                              ),
                            ),
                          ),
                        );

                        final time = DateTime.now();

                        print("NOW: $time");

                        await startTor();

                        print("Start tor took "
                            "${DateTime.now().difference(time).inSeconds} "
                            "seconds");

                        if (mounted) {
                          Navigator.of(context).pop();
                        }
                      },
                child: const Text("Start tor"),
              ),
              Row(
                children: [
                  // Host input field.
                  Expanded(
                    child: TextField(
                      controller: hostController,
                      decoration: const InputDecoration(
                        border: OutlineInputBorder(),
                        hintText: 'Host to request',
                      ),
                    ),
                  ),
                  spacerSmall,
                  TextButton(
                    onPressed: torIsRunning
                        ? () async {
                            // `socks5_proxy` package example, use another socks5
                            // connection of your choice.

                            // Create HttpClient object
                            final client = HttpClient();

                            // Assign connection factory.
                            SocksTCPClient.assignToHttpClient(client, [
                              ProxySettings(InternetAddress.loopbackIPv4,
                                  Tor.instance.port,
                                  password:
                                      null), // TODO Need to get from tor config file.
                            ]);

                            // GET request.
                            final request = await client
                                .getUrl(Uri.parse(hostController.text));
                            final response = await request.close();

                            // Print response.
                            var responseString =
                                await utf8.decodeStream(response);
                            print(responseString);
                            // If host input left to default icanhazip.com, a Tor
                            // exit node IP should be printed to the console.
                            //
                            // https://check.torproject.org is also good for
                            // doublechecking torability.

                            // Close client
                            client.close();
                          }
                        : null,
                    child: const Text("Make proxied request"),
                  ),
                ],
              ),
              // A spacer.
              spacerSmall,
              // A button that demonstrates use of tor_package.
              //
              // Because tor_package is just the package template, it just has
              // an addOne function, so we'll just demonstrate that for now.
              TextButton(
                onPressed: /*torPackageIsRunning // TODO enable.  See also below.
                    ?*/
                    () async {
                  // Add one to the counter.
                  final torPackage = TorPackage();

                  print("can haz tor?");
                  torPackage.startTor();
                  print("purtortedly haz");
                  String hazIp = await torPackage.iCanHazIp();
                  print("haz ip $hazIp");

                  // TODO link to UI.
                  //
                  // For now we'll just print to the console, but we need
                  // to implement tor_package to the point that it can
                  // start and report its own tor instance.  TODO.
                } /*: null*/, // TODO enable.  See also above.
                child: const Text("Test tor_package"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
